name: farmerapp
description: "GreenGrocc Farmer Mobile App - Crop Planning, Products, Orders, Harvest & Earnings."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  http: ^1.4.0
  shared_preferences: ^2.5.3
  intl: any
  image_picker: ^1.2.3
  pdf: ^3.13.1
  printing: ^5.15.1
  share_plus: ^13.3.0
  path_provider: ^2.1.6
  file_picker: ^13.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/
