import {
  Farmer,
  FarmerCrop,
  FarmerProduct,
  FarmerOrder,
  FarmerEarning,
  FarmerManager,
  Pickup,
  PickupDriver,
  Vendor,
} from "../../../farmer-manager-service/src/models.js";
import DeliveryManager from "../../../delivery-service/src/models/DeliveryManager.js";
import DeliveryBoy from "../../../delivery-service/src/models/DeliveryBoy.js";
import StoreOrder from "../../../delivery-service/src/models/StoreOrder.js";
import Staff from "../../../staff-service/src/models/Staff.js";
import {
  Farm,
  Crop,
  Article,
  Batch,
  Warehouse,
  ColdStorage,
  Inventory,
  Procurement,
  CustomerOrder,
  Delivery,
  QualityCheck,
  Employee,
  Customer,
  VendorMaster,
  ErpPayment,
} from "../models/index.js";

function startOfToday() {
  const d = new Date();
  d.setHours(0, 0, 0, 0);
  return d;
}

export async function getCeoDashboard() {
  const today = startOfToday();
  const [
    totalFarmers,
    activeFarmers,
    totalFarms,
    activeCrops,
    totalArticles,
    totalBatches,
    inventoryAgg,
    lowStock,
    procurementAgg,
    todaysOrders,
    pendingOrders,
    completedOrders,
    salesAgg,
    expenseAgg,
    pendingPayments,
    collectionsAgg,
    warehouseStock,
    coldStock,
    deliveries,
    delivered,
    quality,
    customers,
    vendors,
    drivers,
    employees,
    farmerManagers,
    activeFarmerManagers,
    kycPending,
    kycApproved,
    bankVerified,
    farmerProducts,
    farmerOrders,
    farmerOrderValue,
    farmerEarningsPaid,
    farmerEarningsPending,
    liveVendors,
    activeVendors,
    pendingVendors,
    pickupDrivers,
    activePickupDrivers,
    pickupsOpen,
    deliveryManagers,
    activeDeliveryManagers,
    deliveryBoys,
    onlineBoys,
    onDeliveryBoys,
    pendingBoyKyc,
    todayRiderDeliveries,
    storeOrders,
    storeDelivered,
    storePending,
    staffCount,
    activeStaff,
    staffRoles,
    farmerCrops,
  ] = await Promise.all([
    Farmer.countDocuments({}),
    Farmer.countDocuments({ status: { $in: ["Active", "ACTIVE"] } }),
    Farm.countDocuments({ isDeleted: { $ne: true } }),
    Crop.countDocuments({ isDeleted: { $ne: true }, status: { $nin: ["INACTIVE", "CLOSED"] } }),
    Article.countDocuments({ isDeleted: { $ne: true } }),
    Batch.countDocuments({ isDeleted: { $ne: true } }),
    Inventory.aggregate([
      { $match: { isDeleted: { $ne: true } } },
      { $group: { _id: null, stock: { $sum: "$availableStock" }, value: { $sum: "$totalValue" } } },
    ]),
    Inventory.countDocuments({ isDeleted: { $ne: true }, lowStockAlert: true }),
    Procurement.aggregate([
      { $match: { isDeleted: { $ne: true } } },
      { $group: { _id: null, qty: { $sum: "$quantity" }, amount: { $sum: "$purchaseAmount" } } },
    ]),
    CustomerOrder.countDocuments({ createdAt: { $gte: today }, isDeleted: { $ne: true } }),
    CustomerOrder.countDocuments({ isDeleted: { $ne: true }, status: { $nin: ["COMPLETED", "DELIVERED", "CANCELLED"] } }),
    CustomerOrder.countDocuments({ isDeleted: { $ne: true }, status: { $in: ["COMPLETED", "DELIVERED"] } }),
    CustomerOrder.aggregate([
      { $match: { isDeleted: { $ne: true } } },
      { $group: { _id: null, amount: { $sum: "$amount" }, count: { $sum: 1 } } },
    ]),
    Procurement.aggregate([
      { $match: { isDeleted: { $ne: true } } },
      { $group: { _id: null, amount: { $sum: "$purchaseAmount" } } },
    ]),
    ErpPayment.countDocuments({ isDeleted: { $ne: true }, paymentStatus: { $in: ["PENDING", "UNPAID"] } }),
    ErpPayment.aggregate([
      { $match: { isDeleted: { $ne: true }, paymentStatus: { $in: ["PAID", "SETTLED", "SUCCESS"] } } },
      { $group: { _id: null, amount: { $sum: "$amount" } } },
    ]),
    Warehouse.aggregate([{ $match: { isDeleted: { $ne: true } } }, { $group: { _id: null, stock: { $sum: "$currentStock" } } }]),
    ColdStorage.aggregate([{ $match: { isDeleted: { $ne: true } } }, { $group: { _id: null, occupied: { $sum: "$occupiedCapacity" } } }]),
    Delivery.countDocuments({ isDeleted: { $ne: true } }),
    Delivery.countDocuments({ isDeleted: { $ne: true }, deliveryStatus: "DELIVERED" }),
    QualityCheck.aggregate([
      { $match: { isDeleted: { $ne: true } } },
      {
        $group: {
          _id: "$grade",
          count: { $sum: 1 },
          rejected: { $sum: "$rejectedQuantity" },
        },
      },
    ]),
    Customer.countDocuments({ isDeleted: { $ne: true } }),
    VendorMaster.countDocuments({ isDeleted: { $ne: true } }),
    PickupDriver.countDocuments({}),
    Employee.countDocuments({ isDeleted: { $ne: true } }),
    FarmerManager.countDocuments({}),
    FarmerManager.countDocuments({ status: "Active" }),
    Farmer.countDocuments({ isDeleted: { $ne: true }, kycStatus: { $in: ["PENDING", "SUBMITTED"] } }),
    Farmer.countDocuments({ isDeleted: { $ne: true }, kycStatus: "APPROVED" }),
    Farmer.countDocuments({ isDeleted: { $ne: true }, bankVerificationStatus: "VERIFIED" }),
    FarmerProduct.countDocuments({}),
    FarmerOrder.countDocuments({}),
    FarmerOrder.aggregate([{ $group: { _id: null, amount: { $sum: "$totalAmount" } } }]),
    FarmerEarning.aggregate([
      { $match: { status: "Paid" } },
      { $group: { _id: null, amount: { $sum: "$netEarnings" } } },
    ]),
    FarmerEarning.aggregate([
      { $match: { status: { $in: ["Pending", "Available"] } } },
      { $group: { _id: null, amount: { $sum: "$netEarnings" } } },
    ]),
    Vendor.countDocuments({}),
    Vendor.countDocuments({ status: "Active" }),
    Vendor.countDocuments({ status: "Pending" }),
    PickupDriver.countDocuments({}),
    PickupDriver.countDocuments({ status: "Active" }),
    Pickup.countDocuments({ status: { $nin: ["COMPLETED", "DELIVERED", "CANCELLED"] } }),
    DeliveryManager.countDocuments({}),
    DeliveryManager.countDocuments({ isActive: { $ne: false } }),
    DeliveryBoy.countDocuments({}),
    DeliveryBoy.countDocuments({ status: "online" }),
    DeliveryBoy.countDocuments({ status: "on_delivery" }),
    DeliveryBoy.countDocuments({ verificationStatus: "pending" }),
    DeliveryBoy.aggregate([{ $group: { _id: null, qty: { $sum: "$todayCompletedOrders" } } }]),
    StoreOrder.countDocuments({}),
    StoreOrder.countDocuments({ status: "delivered" }),
    StoreOrder.countDocuments({ status: { $nin: ["delivered", "cancelled"] } }),
    Staff.countDocuments({}),
    Staff.countDocuments({ isActive: { $ne: false } }),
    Staff.aggregate([{ $group: { _id: "$role", count: { $sum: 1 } } }]),
    FarmerCrop.countDocuments({}),
  ]);

  const gradeMap = Object.fromEntries((quality || []).map((g) => [g._id || "NONE", g]));
  const gradeTotal = (quality || []).reduce((s, g) => s + (g.count || 0), 0) || 1;
  const revenue = salesAgg[0]?.amount || 0;
  const expenses = expenseAgg[0]?.amount || 0;
  const staffRoleCounts = Object.fromEntries((staffRoles || []).map((row) => [row._id, row.count]));

  const kpis = {
    totalFarmers,
    activeFarmers,
    totalFarms,
    activeCrops,
    totalArticles,
    totalBatches,
    totalInventory: inventoryAgg[0]?.stock || 0,
    inventoryValue: inventoryAgg[0]?.value || 0,
    lowStock,
    procurementQuantity: procurementAgg[0]?.qty || 0,
    procurementAmount: procurementAgg[0]?.amount || 0,
    todaysOrders,
    pendingOrders,
    completedOrders,
    sales: salesAgg[0]?.count || 0,
    revenue,
    expenses,
    profit: revenue - expenses,
    pendingPayments,
    collections: collectionsAgg[0]?.amount || 0,
    warehouseStock: warehouseStock[0]?.stock || 0,
    coldStorageStock: coldStock[0]?.occupied || 0,
    deliveryPerformance: deliveries ? Math.round((delivered / deliveries) * 100) : 0,
    qualityRejections: (quality || []).reduce((s, g) => s + (g.rejected || 0), 0),
    gradeAPercent: Math.round(((gradeMap.A?.count || 0) / gradeTotal) * 100),
    gradeBPercent: Math.round(((gradeMap.B?.count || 0) / gradeTotal) * 100),
    gradeCPercent: Math.round(((gradeMap.C?.count || 0) / gradeTotal) * 100),
    customerGrowth: customers,
    vendorPerformance: vendors,
    driverPerformance: drivers,
    hrHeadcount: employees,
    farmerCrops,
    farmerManagers,
    activeFarmerManagers,
    kycPending,
    kycApproved,
    bankVerified,
    farmerProducts,
    farmerOrders,
    farmerOrderValue: farmerOrderValue[0]?.amount || 0,
    farmerEarningsPaid: farmerEarningsPaid[0]?.amount || 0,
    farmerEarningsPending: farmerEarningsPending[0]?.amount || 0,
    liveVendors,
    activeVendors,
    pendingVendors,
    pickupDrivers,
    activePickupDrivers,
    pickupsOpen,
    deliveryManagers,
    activeDeliveryManagers,
    deliveryBoys,
    onlineBoys,
    onDeliveryBoys,
    pendingBoyKyc,
    todayRiderDeliveries: todayRiderDeliveries[0]?.qty || 0,
    storeOrders,
    storeDelivered,
    storePending,
    staffCount,
    activeStaff,
    staffProductManagers: staffRoleCounts.product_manager || 0,
    staffFarmerManagers: staffRoleCounts.farmer_manager || 0,
    staffSegregationManagers: staffRoleCounts.segregation_manager || 0,
    staffVendors: staffRoleCounts.vendor || 0,
  };

  return {
    generatedAt: new Date(),
    kpis,
    lenses: [
      { id: "all", label: "All insights", count: totalFarmers + farmerManagers + liveVendors + pickupDrivers + deliveryManagers + deliveryBoys + staffCount + customers },
      { id: "farmers", label: "Farmers", count: totalFarmers },
      { id: "farmer_managers", label: "Farmer managers", count: farmerManagers },
      { id: "vendors", label: "Vendors", count: liveVendors },
      { id: "pickup_drivers", label: "Pickup drivers", count: pickupDrivers },
      { id: "delivery_managers", label: "Delivery managers", count: deliveryManagers },
      { id: "delivery_boys", label: "Delivery boys", count: deliveryBoys },
      { id: "office_staff", label: "Office staff", count: staffCount },
      { id: "customers", label: "Customers", count: customers },
    ],
    modules: [
      "Farmer",
      "Procurement",
      "Inventory",
      "Orders",
      "Sales",
      "Revenue",
      "Expense",
      "Profit",
      "Customers",
      "Delivery",
      "Warehouse",
      "Quality",
      "Wastage",
      "HR",
      "Vendor",
      "Finance",
      "Audit",
      "Analytics",
    ],
  };
}
