import {
  Company,
  State,
  District,
  Taluka,
  Village,
  Farm,
  Crop,
  Article,
  Batch,
  Crate,
  QrCode,
  CollectionCentreMaster,
  Warehouse,
  ColdStorage,
  DarkStoreMaster,
  Inventory,
  Procurement,
  PurchaseOrder,
  GoodsReceipt,
  VendorMaster,
  FinanceAccount,
  ErpPayment,
  Invoice,
  Employee,
  Recruitment,
  Attendance,
  Customer,
  CrmActivity,
  UserLogin,
  CustomerOrder,
  Delivery,
  Vehicle,
  DriverMaster,
  QualityCheck,
  Packaging,
  Dispatch,
  ReturnRecord,
  Damage,
  AuditLog,
  ApiRegistry,
  ErpTransaction,
  AnalyticsReport,
} from "../models/index.js";

/**
 * Maps REST resources to models, business ID fields, and ID generator modules.
 * Write-protected IDs cannot be changed after create.
 */
export const RESOURCES = {
  companies: { model: Company, idField: "companyId", module: "COM", label: "Company" },
  states: { model: State, idField: "stateId", module: "ST", label: "State" },
  districts: { model: District, idField: "districtId", module: "DST", label: "District" },
  talukas: { model: Taluka, idField: "talukaId", module: "TLK", label: "Taluka" },
  villages: { model: Village, idField: "villageId", module: "VIL", label: "Village" },
  farms: { model: Farm, idField: "farmId", module: "FM", label: "Farm", refs: { farmerId: "farmers" } },
  crops: { model: Crop, idField: "cropId", module: "CRP", label: "Crop" },
  articles: { model: Article, idField: "articleId", module: "ART", label: "Article" },
  batches: {
    model: Batch,
    idField: "batchId",
    module: "BAT",
    label: "Batch",
    refs: { articleId: "articles", cropId: "crops" },
    statusTracked: true,
  },
  crates: { model: Crate, idField: "crateId", module: "CRT", label: "Crate", refs: { batchId: "batches" } },
  qr_codes: { model: QrCode, idField: "qrId", module: "QR", label: "QR" },
  collection_centres: { model: CollectionCentreMaster, idField: "collectionCentreId", module: "CC", label: "Collection Centre" },
  warehouses: { model: Warehouse, idField: "warehouseId", module: "WH", label: "Warehouse" },
  cold_storages: { model: ColdStorage, idField: "coldStorageId", module: "CS", label: "Cold Storage" },
  dark_stores: { model: DarkStoreMaster, idField: "darkStoreId", module: "DS", label: "Dark Store" },
  inventories: {
    model: Inventory,
    idField: "inventoryId",
    module: "INV",
    label: "Inventory",
    refs: { articleId: "articles" },
    statusTracked: true,
  },
  procurements: {
    model: Procurement,
    idField: "procurementId",
    module: "PRC",
    label: "Procurement",
    statusTracked: true,
  },
  purchase_orders: {
    model: PurchaseOrder,
    idField: "purchaseOrderId",
    module: "PO",
    label: "Purchase Order",
    statusTracked: true,
  },
  goods_receipts: {
    model: GoodsReceipt,
    idField: "grnId",
    module: "GRN",
    label: "GRN",
    statusTracked: true,
  },
  vendors: { model: VendorMaster, idField: "vendorId", module: "VEN", label: "Vendor" },
  finance_accounts: { model: FinanceAccount, idField: "financeId", module: "FIN", label: "Finance" },
  payments: {
    model: ErpPayment,
    idField: "paymentId",
    module: "PAY",
    label: "Payment",
    statusTracked: true,
  },
  invoices: { model: Invoice, idField: "invoiceId", module: "INVCE", label: "Invoice" },
  employees: { model: Employee, idField: "employeeId", module: "EMP", label: "Employee" },
  recruitments: { model: Recruitment, idField: "recruitmentId", module: "REC", label: "Recruitment" },
  attendance: { model: Attendance, idField: "attendanceId", module: "ATT", label: "Attendance" },
  customers: { model: Customer, idField: "customerId", module: "CUS", label: "Customer" },
  crm_activities: { model: CrmActivity, idField: "crmActivityId", module: "CRM", label: "CRM Activity" },
  user_logins: { model: UserLogin, idField: "userLoginId", module: "USR", label: "User Login", hide: ["passwordHash"] },
  customer_orders: {
    model: CustomerOrder,
    idField: "orderId",
    module: "ORD",
    label: "Customer Order",
    statusTracked: true,
  },
  deliveries: {
    model: Delivery,
    idField: "deliveryId",
    module: "DEL",
    label: "Delivery",
    statusTracked: true,
  },
  vehicles: { model: Vehicle, idField: "vehicleId", module: "VEH", label: "Vehicle" },
  drivers: { model: DriverMaster, idField: "driverId", module: "DRV", label: "Driver" },
  quality_checks: {
    model: QualityCheck,
    idField: "qualityCheckId",
    module: "QC",
    label: "Quality Check",
    statusTracked: true,
  },
  packaging: { model: Packaging, idField: "packagingId", module: "PKG", label: "Packaging" },
  dispatches: {
    model: Dispatch,
    idField: "dispatchId",
    module: "DSP",
    label: "Dispatch",
    statusTracked: true,
  },
  returns: { model: ReturnRecord, idField: "returnId", module: "RET", label: "Return" },
  damages: { model: Damage, idField: "damageId", module: "DMG", label: "Damage" },
  audit_logs: { model: AuditLog, idField: "auditId", module: "AUD", label: "Audit Log", readOnly: true },
  api_registry: { model: ApiRegistry, idField: "apiId", module: "API", label: "API Master" },
  erp_transactions: { model: ErpTransaction, idField: "erpTransactionId", module: "ERP", label: "ERP Transaction" },
  analytics: { model: AnalyticsReport, idField: "analyticsId", module: "ANL", label: "Analytics" },
};

export const ENTITY_RESOURCE = {
  company: "companies",
  state: "states",
  district: "districts",
  taluka: "talukas",
  village: "villages",
  farm: "farms",
  crop: "crops",
  article: "articles",
  batch: "batches",
  crate: "crates",
  qr: "qr_codes",
  collectionCentre: "collection_centres",
  warehouse: "warehouses",
  coldStorage: "cold_storages",
  darkStore: "dark_stores",
  inventory: "inventories",
  procurement: "procurements",
  purchaseOrder: "purchase_orders",
  goodsReceipt: "goods_receipts",
  vendor: "vendors",
  finance: "finance_accounts",
  payment: "payments",
  invoice: "invoices",
  employee: "employees",
  recruitment: "recruitments",
  attendance: "attendance",
  customer: "customers",
  crmActivity: "crm_activities",
  userLogin: "user_logins",
  order: "customer_orders",
  delivery: "deliveries",
  vehicle: "vehicles",
  driver: "drivers",
  qualityCheck: "quality_checks",
  packaging: "packaging",
  dispatch: "dispatches",
  return: "returns",
  damage: "damages",
  audit: "audit_logs",
  api: "api_registry",
  erpTransaction: "erp_transactions",
  analytics: "analytics",
};
