import { pickupStatusLabel, PICKUP_STATUS_LABELS } from "../pickup/PickupTimeline";

const PICKUP_KEYS = new Set(Object.keys(PICKUP_STATUS_LABELS));
const PICKUP_LABELS = new Set(Object.values(PICKUP_STATUS_LABELS));

const STATUS_TEXT_COLORS = {
  pending: "text-amber-700",
  PENDING: "text-amber-700",
  SUBMITTED: "text-amber-700",
  APPROVED: "text-emerald-700",
  Approved: "text-emerald-700",
  approved: "text-emerald-700",
  REJECTED: "text-red-600",
  Rejected: "text-red-600",
  rejected: "text-red-600",
  VERIFIED: "text-emerald-700",
  Verified: "text-emerald-700",
  not_uploaded: "text-slate-500",
  Draft: "text-slate-500",
  "Pending Approval": "text-amber-700",
  "Out of Stock": "text-red-600",
  Inactive: "text-slate-500",
  New: "text-sky-700",
  NEW: "text-sky-700",
  Confirmed: "text-indigo-700",
  Processing: "text-purple-700",
  "Ready for Harvest": "text-teal-700",
  "READY FOR HARVEST": "text-teal-700",
  READY_FOR_HARVEST: "text-teal-700",
  Growing: "text-sky-700",
  Planned: "text-indigo-700",
  Harvested: "text-emerald-700",
  Completed: "text-emerald-700",
  COMPLETED: "text-emerald-700",
  Cancelled: "text-red-600",
  CANCELLED: "text-red-600",
  Paid: "text-emerald-700",
  PAID: "text-emerald-700",
  paid: "text-emerald-700",
  "Payment Pending": "text-amber-700",
  "Payment Received": "text-emerald-700",
  "Payment Completed": "text-emerald-700",
  PAYMENT_PENDING: "text-amber-700",
  PAYMENT_COMPLETED: "text-emerald-700",
  Failed: "text-red-600",
  "In Stock": "text-emerald-700",
  "Low Stock": "text-amber-700",
  Active: "text-emerald-700",
  Paused: "text-slate-500",
  PENDING_APPROVAL: "text-amber-700",
  ACCEPTED: "text-indigo-700",
  PREPARING: "text-purple-700",
  PACKING: "text-purple-700",
  DISPATCHED: "text-purple-700",
  ORDER_VERIFIED: "text-teal-700",
  ARRIVED: "text-sky-700",
  READY_FOR_PICKUP: "text-teal-700",
  "Ready for Pickup": "text-teal-700",
  PICKUP_SCHEDULED: "text-indigo-700",
  DRIVER_ASSIGNED: "text-indigo-700",
  DRIVER_ARRIVED: "text-sky-700",
  QR_VERIFIED: "text-teal-700",
  PICKUP_CONFIRMED: "text-emerald-700",
  PICKED_UP: "text-emerald-700",
  IN_TRANSIT: "text-purple-700",
  ARRIVED_AT_CENTRE: "text-emerald-700",
  COLLECTION_CENTRE_RECEIVED: "text-emerald-700",
  RECEIVED_AT_COLLECTION_CENTRE: "text-emerald-700",
  UNLOADING: "text-purple-700",
  WEIGHT_CHECK: "text-amber-700",
  RECEIVED: "text-emerald-700",
  QUALITY_PENDING: "text-amber-700",
  INSPECTION: "text-sky-700",
  GRADING: "text-purple-700",
  GRADE_CONFIRMED: "text-emerald-700",
  ORDER_COMPLETED: "text-emerald-700",
  NOT_STARTED: "text-slate-500",
  // Crop Planning statuses
  "Planning Created": "text-indigo-700",
  "Soil Testing Pending": "text-amber-700",
  "Soil Testing Completed": "text-emerald-700",
  "Soil Report Uploaded": "text-sky-700",
  "Soil Report Under Review": "text-amber-700",
  "Soil Report Approved": "text-emerald-700",
  "Land Preparation": "text-indigo-700",
  "Crop & Variety Selected": "text-indigo-700",
  "Seed/Input Planning": "text-purple-700",
  "Sowing/Plantation Started": "text-sky-700",
  "Sowing/Plantation Completed": "text-teal-700",
  "Crop Growing": "text-green-700",
  "Irrigation in Progress": "text-sky-700",
  "Fertilizer Application": "text-purple-700",
  "Pesticide Application": "text-amber-700",
  "Pest/Disease Monitoring": "text-amber-700",
  "Field Inspection Pending": "text-amber-700",
  "Field Inspection Completed": "text-emerald-700",
  "Crop Growth Monitoring": "text-sky-700",
  "Pre-Harvest Inspection": "text-purple-700",
  "Harvest Readiness": "text-teal-700",
  "Harvesting Started": "text-sky-700",
  "Harvesting In Progress": "text-purple-700",
  "Harvesting Completed": "text-emerald-700",
  "Harvest Quantity Recorded": "text-teal-700",
  "Harvest Batch Created": "text-emerald-700",
};

const STATUS_LABELS = {
  PAID: "Paid",
  paid: "Paid",
  Paid: "Paid",
  PENDING: "Pending",
  pending: "Pending",
  Pending: "Pending",
  PAYMENT_PENDING: "Pending",
  "Payment Pending": "Pending",
  PAYMENT_COMPLETED: "Paid",
  "Payment Completed": "Paid",
  NEW: "New",
  ACCEPTED: "Accepted",
  PREPARING: "Preparing",
  REJECTED: "Rejected",
  CANCELLED: "Cancelled",
  COMPLETED: "Completed",
  READY_FOR_PICKUP: "Ready for pickup",
  DRIVER_ASSIGNED: "Assigned",
  PICKUP_SCHEDULED: "Assigned",
  DISPATCHED: "On the way to farm",
  DRIVER_ARRIVED: "Reached the farm",
  ARRIVED: "Reached the farm",
  ORDER_VERIFIED: "Order checked",
  QR_VERIFIED: "QR verified",
  PICKED_UP: "Pickup confirmed",
  PICKUP_CONFIRMED: "Pickup confirmed",
  IN_TRANSIT: "On the way to centre",
  ARRIVED_AT_CENTRE: "At collection centre",
  COLLECTION_CENTRE_RECEIVED: "Received",
  RECEIVED_AT_COLLECTION_CENTRE: "Received",
  QUALITY_PENDING: "Pending",
  QUALITY_CHECK: "Quality Check",
  INSPECTION: "Quality Check",
  GRADING: "Grading",
  GRADE_CONFIRMED: "Grading Completed",
  ORDER_COMPLETED: "Grading Completed",
};

function StatusBadge({ status, className = "" }) {
  const key = String(status || "").trim();
  const pickupLabel = pickupStatusLabel(key);
  const isPickup = PICKUP_KEYS.has(key) || PICKUP_LABELS.has(pickupLabel);
  const color = STATUS_TEXT_COLORS[key] || (isPickup ? "text-emerald-700" : "text-slate-700");
  const label =
    key === "not_uploaded"
      ? "Not Uploaded"
      : isPickup
        ? pickupLabel
        : STATUS_LABELS[key] || key.replace(/_/g, " ");

  return (
    <span className={`inline-block truncate font-bold text-[11px] ${color} ${className}`}>
      {label}
    </span>
  );
}

export default StatusBadge;
