// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_vaZgbVAGjcVH928JNqpzSDwMJVfKULE',
    appId: '1:50988055235:web:51c630cf075f213eac0076',
    messagingSenderId: '50988055235',
    projectId: 'greengrocc-27df8',
    authDomain: 'greengrocc-27df8.firebaseapp.com',
    storageBucket: 'greengrocc-27df8.firebasestorage.app',
    measurementId: 'G-32FJW5WFX4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2V68_-ob72N1qvGmfKF_IbIwDo7WR9hs',
    appId: '1:50988055235:android:11215dbd4857a9cfac0076',
    messagingSenderId: '50988055235',
    projectId: 'greengrocc-27df8',
    storageBucket: 'greengrocc-27df8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiPdrRkJdeDzA77SF-A8OGbtonk_v4S6U',
    appId: '1:50988055235:ios:633fc0e4b7fee772ac0076',
    messagingSenderId: '50988055235',
    projectId: 'greengrocc-27df8',
    storageBucket: 'greengrocc-27df8.firebasestorage.app',
    iosBundleId: 'com.greenrow.delivery',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBiPdrRkJdeDzA77SF-A8OGbtonk_v4S6U',
    appId: '1:50988055235:ios:f6e7ee903258ca6cac0076',
    messagingSenderId: '50988055235',
    projectId: 'greengrocc-27df8',
    storageBucket: 'greengrocc-27df8.firebasestorage.app',
    iosBundleId: 'com.example.deliveryapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_vaZgbVAGjcVH928JNqpzSDwMJVfKULE',
    appId: '1:50988055235:web:b07e62ec1817235eac0076',
    messagingSenderId: '50988055235',
    projectId: 'greengrocc-27df8',
    authDomain: 'greengrocc-27df8.firebaseapp.com',
    storageBucket: 'greengrocc-27df8.firebasestorage.app',
    measurementId: 'G-7YK4FLSXDF',
  );
}
