/** Zepto-style store themes for mobile home header matching reference screenshots */
export const STORE_KEYS = ["main", "festive", "mall", "cafe"];

export const STORE_THEMES = {
  main: {
    key: "main",
    time: "10 minutes",
    deliveryBg: "bg-[#DCFCE7]",
    contentBg: "bg-[#DCFCE7]",
    textColor: "text-emerald-950",
    subTextColor: "text-emerald-900",
    profileClass: "bg-[#0C831F] text-white border-0",
    activeTabBg: "bg-[#DCFCE7]",
    activeTabBorder: "border-transparent",
    inactiveTabClass: "bg-white text-slate-900 shadow-sm border border-transparent",
    searchBorder: "border-transparent",
    placeholder: 'Search for "Fruits", "Vegetables"...',
    categoryBorder: "border-emerald-900/10",
    categoryText: "text-emerald-950",
    categoryInactive: "text-emerald-900/70",
    categoryIndicator: "bg-[#0C831F]",
  },
  festive: {
    key: "festive",
    time: "15 minutes",
    deliveryBg: "bg-[#940B0B]",
    contentBg: "bg-[#940B0B]",
    textColor: "text-white",
    subTextColor: "text-red-100",
    profileClass: "bg-[#6D0000] border-2 border-white/60 text-white",
    activeTabBg: "bg-[#6D0000]",
    activeTabBorder: "border-transparent",
    inactiveTabClass: "bg-white text-slate-900 shadow-sm border border-transparent",
    searchBorder: "border-transparent",
    placeholder: 'Search for "Rakhi"',
    categoryBorder: "border-white/20",
    categoryText: "text-white",
    categoryInactive: "text-white/75",
    categoryIndicator: "bg-amber-300",
  },
  mall: {
    key: "mall",
    time: "15 minutes",
    deliveryBg: "bg-black",
    contentBg: "bg-[#3C22B4]",
    textColor: "text-white",
    subTextColor: "text-slate-200",
    profileClass: "bg-black border border-white/40 text-white",
    activeTabBg: "bg-[#3C22B4]",
    activeTabBorder: "border-transparent",
    inactiveTabClass: "bg-white text-slate-900 shadow-sm border border-transparent",
    searchBorder: "border-transparent",
    placeholder: 'Search for "Rakhi"',
    categoryBorder: "border-white/20",
    categoryText: "text-white",
    categoryInactive: "text-white/75",
    categoryIndicator: "bg-amber-300",
  },
  cafe: {
    key: "cafe",
    time: "15 minutes",
    deliveryBg: "bg-[#FFE3B3]",
    contentBg: "bg-[#FFE3B3]",
    textColor: "text-slate-950",
    subTextColor: "text-slate-900",
    profileClass: "bg-black text-white border-0",
    activeTabBg: "bg-[#FFE3B3]",
    activeTabBorder: "border-transparent",
    inactiveTabClass: "bg-white text-slate-900 shadow-sm border border-transparent",
    searchBorder: "border-transparent",
    placeholder: 'Search for "Rakhi"',
    categoryBorder: "border-amber-900/10",
    categoryText: "text-slate-950",
    categoryInactive: "text-slate-700",
    categoryIndicator: "bg-slate-900",
  },
};

export function resolveStoreTheme(storeKey) {
  return STORE_THEMES[storeKey] || STORE_THEMES.main;
}
