/** Zepto-style store themes for mobile home header matching reference screenshots */
export const STORE_KEYS = ["main", "festive", "mall"];

export const STORE_THEMES = {
  main: {
    key: "main",
    time: "10 minutes",
    deliveryBg: "bg-gradient-to-b from-[#064E3B] via-[#047857] to-[#059669]",
    searchBg: "bg-gradient-to-b from-[#059669] via-[#10B981] to-[#34D399]",
    categoryBg: "bg-gradient-to-b from-[#34D399] via-[#A7F3D0] to-[#DCFCE7]",
    bannerBg: "bg-gradient-to-b from-[#DCFCE7] via-[#34D399] to-[#047857]",
    contentBg: "bg-gradient-to-b from-[#059669] via-[#34D399] to-[#DCFCE7]",
    textColor: "text-white",
    subTextColor: "text-emerald-100",
    profileClass: "bg-emerald-600 text-white border border-emerald-400/40",
    activeTabBg: "bg-[#059669]",
    activeTabBorder: "border-emerald-400/70",
    inactiveTabClass: "bg-white text-slate-900 shadow-xs border border-slate-200/90",
    searchBorder: "border-transparent",
    placeholder: 'Search for "Fruits", "Vegetables"...',
    categoryBorder: "border-black/5",
    categoryText: "text-emerald-950",
    categoryInactive: "text-emerald-900/70",
    categoryIndicator: "bg-[#0C831F]",
  },
  festive: {
    key: "festive",
    time: "15 minutes",
    deliveryBg: "bg-gradient-to-b from-[#7C2D12] via-[#9A3412] to-[#C2410C]",
    searchBg: "bg-gradient-to-b from-[#C2410C] via-[#EA580C] to-[#F97316]",
    categoryBg: "bg-gradient-to-b from-[#F97316] via-[#FDBA74] to-[#FFEDD5]",
    bannerBg: "bg-white",
    contentBg: "bg-white",
    textColor: "text-white",
    subTextColor: "text-orange-100",
    profileClass: "bg-orange-600 text-white border border-orange-400/40",
    activeTabBg: "bg-[#C2410C]",
    activeTabBorder: "border-orange-300/80",
    inactiveTabClass: "bg-white text-slate-900 shadow-xs border border-slate-200/90",
    searchBorder: "border-transparent",
    placeholder: 'Search for "Ready2Cook"',
    categoryBorder: "border-black/5",
    categoryText: "text-[#7C2D12]",
    categoryInactive: "text-[#9A3412]/70",
    categoryIndicator: "bg-[#EA580C]",
  },
  mall: {
    key: "mall",
    time: "15 minutes",
    deliveryBg: "bg-gradient-to-b from-[#020617] via-[#0F172A] to-[#1E1B4B]",
    searchBg: "bg-gradient-to-b from-[#1E1B4B] via-[#312E81] to-[#4338CA]",
    categoryBg: "bg-gradient-to-b from-[#4338CA] via-[#6366F1] to-[#C7D2FE]",
    bannerBg: "bg-gradient-to-b from-[#C7D2FE] via-[#6366F1] to-[#1E1B4B]",
    contentBg: "bg-gradient-to-b from-[#1E1B4B] via-[#4338CA] to-[#C7D2FE]",
    textColor: "text-white",
    subTextColor: "text-slate-200",
    profileClass: "bg-black border border-white/40 text-white",
    activeTabBg: "bg-[#1E1B4B]",
    activeTabBorder: "border-violet-400/40",
    inactiveTabClass: "bg-white text-slate-900 shadow-sm border border-transparent",
    searchBorder: "border-transparent",
    placeholder: 'Search for "Ready2Cook"',
    categoryBorder: "border-white/20",
    categoryText: "text-white",
    categoryInactive: "text-white/75",
    categoryIndicator: "bg-amber-300",
  },
};

export function resolveStoreTheme(storeKey) {
  return STORE_THEMES[storeKey] || STORE_THEMES.main;
}
