import {
  LayoutDashboard,
  Package,
  FolderTree,
  Store,
  ArrowUpDown,
  FileSpreadsheet,
  Ticket,
  Coins,
  Gift,
  BadgePercent,
  Boxes,
  Truck,
  MapPinned,
  Building2,
  Headset,
  Users,
  Landmark,
  RotateCcw,
  BarChart3,
  Search,
  Tractor,
  QrCode,
  Warehouse,
  ShoppingCart,
  IndianRupee,
  ClipboardList,
  Thermometer,
  Leaf,
  ShieldCheck,
} from 'lucide-react';

export const NAV_GROUPS = [
  {
    id: 'erp',
    label: 'ERP',
    items: [
      { name: 'CEO Dashboard', href: '/', icon: LayoutDashboard, end: true, implemented: true, description: 'Executive overview of farms, inventory, and orders.' },
      { name: 'Traceability', href: '/traceability', icon: Search, implemented: true, description: 'Trace batches from farm to customer.' },
      { name: 'Locations', href: '/erp/locations', icon: MapPinned, implemented: true, description: 'Master data for villages, talukas, and districts.' },
      { name: 'Farmers', href: '/erp/farmers', icon: Tractor, implemented: true, description: 'Farmer registry and 360 profiles.' },
      { name: 'Crops', href: '/erp/crops', icon: Leaf, implemented: true, description: 'Crop master list used across ERP.' },
      { name: 'Articles', href: '/erp/articles', icon: Package, implemented: true, description: 'SKU and article master for ERP.' },
      { name: 'Batches', href: '/erp/batches', icon: Boxes, implemented: true, description: 'Harvest and processing batches.' },
      { name: 'QR Codes', href: '/erp/qr_codes', icon: QrCode, implemented: true, description: 'QR codes linked to batches and products.' },
      { name: 'Collection Centres', href: '/erp/collection_centres', icon: Warehouse, implemented: true, description: 'Inbound collection points.' },
      { name: 'Warehouses', href: '/erp/warehouses', icon: Warehouse, implemented: true, description: 'Warehouse master and capacity.' },
      { name: 'Cold Storage', href: '/erp/cold_storages', icon: Thermometer, implemented: true, description: 'Cold storage locations and status.' },
      { name: 'Inventory', href: '/erp/inventories', icon: ClipboardList, implemented: true, description: 'ERP inventory positions.' },
      { name: 'Orders', href: '/erp/customer_orders', icon: ShoppingCart, implemented: true, description: 'Customer orders in ERP.' },
      { name: 'Payments', href: '/erp/payments', icon: IndianRupee, implemented: true, description: 'ERP payment records.' },
      { name: 'Drivers', href: '/erp/drivers', icon: Truck, implemented: true, description: 'Pickup and transport drivers.' },
      { name: 'Customers', href: '/erp/customers', icon: Users, implemented: true, description: 'ERP customer directory.' },
      { name: 'Audit', href: '/erp/audit_logs', icon: ShieldCheck, implemented: true, description: 'ERP audit trail.' },
    ],
  },
  {
    id: 'overview',
    label: 'Overview',
    items: [
      {
        name: 'Admin Welcome',
        href: '/welcome',
        icon: LayoutDashboard,
        implemented: true,
        description: 'Admin portal shortcuts for catalog, promotions, and operations.',
      },
    ],
  },
  {
    id: 'catalog',
    label: 'Catalog',
    items: [
      {
        name: 'Product Management',
        href: '/products',
        icon: Package,
        implemented: true,
        description: 'Create, edit, and publish products, pricing, stock, and media.',
      },
      {
        name: 'Sections & Categories',
        href: '/categories',
        icon: FolderTree,
        implemented: true,
        description: 'Organize store sections, categories, and how they appear on the app.',
      },
      {
        name: 'Dark Stores',
        href: '/dark-stores',
        icon: Store,
        implemented: true,
        description: 'Manage dark store locations, coverage, and store operations.',
      },
      {
        name: 'Bulk Import / Export',
        href: '/bulk-import-export',
        icon: ArrowUpDown,
        description: 'Import and export products, inventory, and catalogs in bulk.',
        capabilities: [
          'Upload product and inventory files in bulk',
          'Export catalogs, stock, and price lists',
          'Validate rows before they go live',
          'Download error reports for failed rows',
        ],
      },
      {
        name: 'CSV Import & Export',
        href: '/csv-import-export',
        icon: FileSpreadsheet,
        description: 'Upload and download CSV files for products, orders, and customers.',
        capabilities: [
          'Import products, customers, and orders from CSV',
          'Export live data to CSV templates',
          'Map columns to GreenGrocc fields',
          'Keep a history of recent CSV jobs',
        ],
      },
    ],
  },
  {
    id: 'promotions',
    label: 'Promotions',
    items: [
      {
        name: 'Coupons & Offers',
        href: '/coupons',
        icon: Ticket,
        implemented: true,
        description: 'Create discount codes, offer rules, and campaign limits.',
      },
      {
        name: 'Reward Points',
        href: '/rewards',
        icon: Coins,
        implemented: true,
        description: 'Set earning, redemption, and terms for the loyalty points program.',
      },
      {
        name: 'Gift Cards',
        href: '/gift-cards',
        icon: Gift,
        description: 'Issue, manage, and track gift cards across stores and customers.',
        capabilities: [
          'Create gift cards with custom denominations',
          'Set expiry, usage limits, and redemption rules',
          'Track balance, status, and redemption history',
          'Disable or refund unused gift cards',
        ],
      },
      {
        name: 'Dynamic Pricing',
        href: '/dynamic-pricing',
        icon: BadgePercent,
        description: 'Quantity-based discounts such as Buy 10 units → Get 5% off.',
        capabilities: [
          'Buy X units and get a % or flat discount',
          'Apply rules by product, category, or store',
          'Set start and end dates for each rule',
          'Preview the final price before publishing',
        ],
      },
      {
        name: 'Bulk Selling',
        href: '/bulk-selling',
        icon: Boxes,
        description: 'Wholesale and B2B orders with volume pricing for bulk buyers.',
        capabilities: [
          'Create wholesale price slabs by quantity',
          'Manage B2B buyers and minimum order quantities',
          'Reserve stock for bulk orders',
          'Track bulk order fulfilment separately',
        ],
      },
    ],
  },
  {
    id: 'operations',
    label: 'Operations',
    items: [
      {
        name: 'Delivery Management',
        href: '/delivery-management',
        icon: Truck,
        description: 'Assign orders, manage delivery slots, zones, and rider allocation.',
        capabilities: [
          'Assign orders to delivery partners',
          'Configure delivery zones and time slots',
          'Monitor pending, in-transit, and delivered orders',
          'Handle failed deliveries and reassignments',
        ],
      },
      {
        name: 'Delivery Tracking',
        href: '/delivery-tracking',
        icon: MapPinned,
        description: 'Live location tracking of delivery partners on the map.',
        capabilities: [
          'View live GPS location of delivery boys',
          'See active routes and ETAs on a map',
          'Filter riders by store, status, or zone',
          'Open a rider trail for delayed orders',
        ],
      },
      {
        name: 'Multi Vendor',
        href: '/multi-vendor',
        icon: Building2,
        description: 'Onboard vendors, manage commissions, approvals, and storefronts.',
        capabilities: [
          'Onboard and approve vendor accounts',
          'Set commission rates and payout cycles',
          'Review vendor products before they go live',
          'Pause or suspend underperforming vendors',
        ],
      },
      {
        name: 'Store Support',
        href: '/store-support',
        icon: Headset,
        description: 'Tickets, chat, and issue resolution for dark stores and customers.',
        capabilities: [
          'Open and assign support tickets by store',
          'Track SLA, priority, and resolution status',
          'Handle customer complaints from one inbox',
          'Escalate issues to operations or finance',
        ],
      },
      {
        name: 'HR Management',
        href: '/hr-management',
        icon: Users,
        description: 'Staff directory, roles, attendance, and payroll for store and delivery teams.',
        capabilities: [
          'Maintain staff profiles and role access',
          'Track attendance and shift rosters',
          'Manage payroll inputs for store and delivery staff',
          'Assign employees to dark stores',
        ],
      },
    ],
  },
  {
    id: 'finance',
    label: 'Finance',
    items: [
      {
        name: 'Finance Management',
        href: '/finance',
        icon: Landmark,
        description: 'Payouts, settlements, GST, and store-wise financial overview.',
        capabilities: [
          'View store and vendor settlements',
          'Track payouts, invoices, and GST summaries',
          'Reconcile collections vs orders',
          'Export finance reports for accounting',
        ],
      },
      {
        name: 'Refund & Warranty',
        href: '/refund-warranty',
        icon: RotateCcw,
        description: 'Process refunds, returns, and warranty claims from one place.',
        capabilities: [
          'Approve or reject refund requests',
          'Track returns against original orders',
          'Log warranty claims and replacements',
          'Push refund status back to the customer',
        ],
      },
      {
        name: 'Reports',
        href: '/reports',
        icon: BarChart3,
        description: 'Sales, inventory, delivery, and vendor reports with date filters.',
        capabilities: [
          'Sales and revenue reports by store',
          'Inventory movement and stock-out reports',
          'Delivery performance and SLA reports',
          'Vendor and promotion performance reports',
        ],
      },
    ],
  },
];
