import {
  LayoutDashboard,
  Package,
  Store,
  ArrowUpDown,
  FileSpreadsheet,
  Ticket,
  Coins,
  Gift,
  BadgePercent,
  Boxes,
  Truck,
  MapPinned,
  Building2,
  Headset,
  Users,
  Landmark,
  RotateCcw,
  BarChart3,
  Search,
  Tractor,
  QrCode,
  Warehouse,
  ShoppingCart,
  IndianRupee,
  ClipboardList,
  Thermometer,
  Leaf,
  ShieldCheck,
  Bike,
  CalendarDays,
  Megaphone,
  Palmtree,
  UserRound,
  Wallet,
  UserPlus,
  Clock3,
  TrendingUp,
  PlusCircle,
  ChartPie,
} from 'lucide-react';

export const NAV_GROUPS = [
  {
    id: 'erp',
    label: 'ERP',
    items: [
      { name: 'CEO Dashboard', href: '/', icon: LayoutDashboard, end: true, implemented: true, description: 'Executive overview of farms, inventory, and orders.' },
      { name: 'Traceability', href: '/traceability', icon: Search, implemented: true, description: 'Trace batches from farm to customer.' },
      { name: 'Locations', href: '/erp/locations', icon: MapPinned, implemented: true, description: 'Master data for villages, talukas, and districts.' },
      { name: 'Farms', href: '/erp/farms', icon: Leaf, implemented: true, description: 'Farm master records linked to farmers.' },
      { name: 'Crops', href: '/erp/crops', icon: Leaf, implemented: true, description: 'Crop master list used across ERP.' },
      { name: 'Articles', href: '/erp/articles', icon: Package, implemented: true, description: 'SKU and article master for ERP.' },
      { name: 'Batches', href: '/erp/batches', icon: Boxes, implemented: true, description: 'Harvest and processing batches.' },
      { name: 'QR Codes', href: '/erp/qr_codes', icon: QrCode, implemented: true, description: 'QR codes linked to batches and products.' },
      { name: 'Collection Centres', href: '/erp/collection_centres', icon: Warehouse, implemented: true, description: 'Inbound collection points.' },
      { name: 'Warehouses', href: '/erp/warehouses', icon: Warehouse, implemented: true, description: 'Warehouse master and capacity.' },
      { name: 'Cold Storage', href: '/erp/cold_storages', icon: Thermometer, implemented: true, description: 'Cold storage locations and status.' },
      { name: 'Inventory positions', href: '/erp/inventories', icon: ClipboardList, implemented: true, description: 'ERP inventory positions by facility.' },
      { name: 'Orders', href: '/erp/customer_orders', icon: ShoppingCart, implemented: true, description: 'Customer orders in ERP.' },
      { name: 'Payments', href: '/erp/payments', icon: IndianRupee, implemented: true, description: 'ERP payment records.' },
      { name: 'Drivers', href: '/erp/drivers', icon: Truck, implemented: true, description: 'Pickup and transport drivers.' },
      { name: 'Customers', href: '/erp/customers', icon: Users, implemented: true, description: 'ERP customer directory.' },
      { name: 'Audit', href: '/erp/audit_logs', icon: ShieldCheck, implemented: true, description: 'ERP audit trail.' },
    ],
  },
  {
    id: 'overview',
    label: 'Overview',
    items: [
      {
        name: 'Admin Welcome',
        href: '/welcome',
        icon: LayoutDashboard,
        implemented: true,
        description: 'Admin portal shortcuts for catalog, promotions, and operations.',
      },
      {
        name: 'Analytics',
        href: '/analytics',
        icon: ChartPie,
        implemented: true,
        description: 'Sales, products, customers, delivery, supply chain and finance insights with filters.',
      },
    ],
  },
  {
    id: 'catalog',
    label: 'Catalog',
    items: [
      {
        name: 'Product Management',
        href: '/products',
        icon: Package,
        implemented: true,
        description: 'Create, edit, and publish products, pricing, stock, and media.',
      },
      {
        name: 'Market Prices',
        href: '/market-prices',
        icon: TrendingUp,
        implemented: true,
        description: 'Daily APMC mandi rates, product varieties, and price trends.',
        capabilities: [
          'Add and manage APMC markets, crops, and varieties',
          'Track minimum, maximum, and modal market rates',
          'Monitor price trends (rising, stable, falling)',
          'Sync daily mandi prices for farmers and operations',
        ],
      },
      {
        name: 'Pre-Order Slots',
        href: '/pre-order-slots',
        icon: Clock3,
        implemented: true,
        description: 'Configure delivery time slots for next-day pre-orders.',
      },
      {
        name: 'Pre-orders',
        href: '/pre-orders',
        icon: CalendarDays,
        implemented: true,
        description: 'Every pre-order by delivery slot: bookings vs capacity, vendor confirmation and progress.',
      },
      {
        name: 'Inventory',
        href: '/inventory',
        icon: ClipboardList,
        implemented: true,
        description: 'Farmers, vendors, and dark-store stock in one place.',
        capabilities: [
          'Browse farmers, vendors, and dark stores',
          'Open any profile to see full inventory',
          'Edit stock quantities quickly',
          'Track low-stock and out-of-stock items',
        ],
      },
      {
        name: 'Bulk Import / Export',
        href: '/bulk-import-export',
        icon: ArrowUpDown,
        description: 'Import and export products, inventory, and catalogs in bulk.',
        capabilities: [
          'Upload product and inventory files in bulk',
          'Export catalogs, stock, and price lists',
          'Validate rows before they go live',
          'Download error reports for failed rows',
        ],
      },
      {
        name: 'CSV Import & Export',
        href: '/csv-import-export',
        icon: FileSpreadsheet,
        description: 'Upload and download CSV files for products, orders, and customers.',
        capabilities: [
          'Import products, customers, and orders from CSV',
          'Export live data to CSV templates',
          'Map columns to GreenGrocc fields',
          'Keep a history of recent CSV jobs',
        ],
      },
    ],
  },
  {
    id: 'promotions',
    label: 'Promotions',
    items: [
      {
        name: 'Coupons & Offers',
        href: '/coupons',
        icon: Ticket,
        implemented: true,
        description: 'Create discount codes, offer rules, and campaign limits.',
      },
      {
        name: 'Reward Points',
        href: '/rewards',
        icon: Coins,
        implemented: true,
        description: 'Set earning, redemption, and terms for the loyalty points program.',
      },
      {
        name: 'Gift Cards',
        href: '/gift-cards',
        icon: Gift,
        description: 'Issue, manage, and track gift cards across stores and customers.',
        capabilities: [
          'Create gift cards with custom denominations',
          'Set expiry, usage limits, and redemption rules',
          'Track balance, status, and redemption history',
          'Disable or refund unused gift cards',
        ],
      },
      {
        name: 'Dynamic Pricing',
        href: '/dynamic-pricing',
        icon: BadgePercent,
        description: 'Quantity-based discounts such as Buy 10 units → Get 5% off.',
        capabilities: [
          'Buy X units and get a % or flat discount',
          'Apply rules by product, category, or store',
          'Set start and end dates for each rule',
          'Preview the final price before publishing',
        ],
      },
      {
        name: 'Return & Warranty',
        href: '/refund-warranty',
        icon: RotateCcw,
        implemented: true,
        description: 'Normal/bulk return requests with accept → delivery pickup flow.',
        capabilities: [
          'Browse by normal or bulk users',
          'Review requests date-wise',
          'Accept, reject, or keep pending',
          'Accepted jobs go to delivery manager pickup',
        ],
      },
    ],
  },
  {
    id: 'operations',
    label: 'Operations',
    items: [
      {
        name: 'Delivery Management',
        href: '/delivery-management',
        icon: Truck,
        implemented: true,
        description: 'Assign orders, manage delivery slots, zones, and rider allocation.',
        capabilities: [
          'Assign orders to delivery partners',
          'Configure delivery zones and time slots',
          'Monitor pending, in-transit, and delivered orders',
          'Handle failed deliveries and reassignments',
        ],
      },
      {
        name: 'Delivery Team',
        href: '/delivery-team',
        icon: Bike,
        implemented: true,
        description: 'Delivery managers, dark stores, and delivery boy profiles.',
      },
      {
        name: 'Delivery Tracking',
        href: '/delivery-tracking',
        icon: MapPinned,
        implemented: true,
        description: 'Live location tracking of delivery partners on the map.',
        capabilities: [
          'View live GPS location of delivery boys',
          'See active routes and ETAs on a map',
          'Filter riders by store, status, or zone',
          'Open a rider trail for delayed orders',
        ],
      },
      {
        name: 'User Management',
        href: '/user-management',
        icon: UserRound,
        implemented: true,
        description: 'Browse normal and bulk users by zone and dark store.',
        capabilities: [
          'Switch between normal and bulk customers',
          'Browse zones such as Mumbai and Pune',
          'Open dark stores inside each zone',
          'Filter users by area, order quantity, and date',
          'Search by name, phone, or order ID',
        ],
      },
      {
        name: 'Assets Management',
        href: '/assets-management',
        icon: Boxes,
        implemented: true,
        description: 'Assign store assets by zone, dark store, and role.',
        capabilities: [
          'Select zone then dark store',
          'Choose delivery manager, delivery boy, customer, or admin',
          'Add assets with name, phone, type, and status',
          'Track assigned, returned, lost, and repair items',
        ],
      },
      {
        name: 'Multi Vendor / Collection Centre',
        href: '/multi-vendor',
        icon: Building2,
        implemented: true,
        description: 'Every vendor is a collection centre. Add and manage all of them.',
        capabilities: [
          'Add multi vendors (collection centres)',
          'See all vendors / collection centres in one list',
          'Set commission rates and approve or suspend centres',
        ],
        children: [
          {
            name: 'Dashboard',
            href: '/collection-dashboard',
            icon: LayoutDashboard,
            implemented: true,
            description: 'Collection centres, farmers, managers and dark stores at a glance.',
          },
          {
            name: 'Multi Vendor / Collection Centre',
            href: '/multi-vendor',
            icon: Building2,
            implemented: true,
            description: 'Every vendor is a collection centre. Add and manage all of them.',
          },
          {
            name: 'All Farmers',
            href: '/collection-farmers',
            icon: Tractor,
            implemented: true,
            description: 'Every farmer and the collection centre they supply.',
          },
          {
            name: 'All Farmer Managers',
            href: '/collection-farmer-managers',
            icon: UserRound,
            implemented: true,
            description: 'Farmer managers by collection centre, with their farmer counts.',
          },
          {
            name: 'Dark Stores',
            href: '/dark-stores',
            icon: Store,
            implemented: true,
            description: 'Manage dark store locations, coverage, and store operations.',
          },
          {
            name: 'Dark Store Requests',
            href: '/dark-store-requests',
            icon: ClipboardList,
            implemented: true,
            description: 'Approve or reject dark stores requested by collection centres.',
          },
          {
            name: 'Product Requests',
            href: '/vendor-product-requests',
            icon: Package,
            implemented: true,
            description: 'Approve or reject catalog products requested by collection centres.',
          },
          {
            name: 'Crop Requests',
            href: '/vendor-crop-requests',
            icon: Leaf,
            implemented: true,
            description: 'Approve or reject crops requested by collection centres.',
          },
        ],
      },
      {
        name: 'Store Support',
        href: '/store-support',
        icon: Headset,
        implemented: true,
        description: 'Support inbox by role — Users site and every staff panel.',
        capabilities: [
          'First screen lists all roles with request counts',
          'Open a role to review ticket briefs and update status',
          'Includes customer (Users) and staff panel support requests',
        ],
      },
      {
        name: 'HR Management',
        href: '/hr-management',
        icon: Users,
        implemented: true,
        description: 'People, leave, payroll, recruitment, and attendance.',
        capabilities: [
          'Maintain staff profiles and role access',
          'Track attendance and shift rosters',
          'Manage payroll inputs for store and delivery staff',
          'Assign employees to dark stores',
        ],
        children: [
          { name: 'Dashboard', href: '/hr-management', icon: LayoutDashboard, end: true },
          { name: 'Calendar', href: '/hr-management/calendar', icon: CalendarDays },
          { name: 'Announcements', href: '/hr-management/announcements', icon: Megaphone },
          { name: 'Leave', href: '/hr-management/leave', icon: Palmtree },
          { name: 'My Leave', href: '/hr-management/my-leave', icon: Palmtree },
          { name: 'Employees', href: '/hr-management/employees', icon: UserRound },
          { name: 'Salary management', href: '/hr-management/payroll', icon: Wallet },
          { name: 'Recruitment', href: '/hr-management/recruitment', icon: UserPlus },
          { name: 'Attendance & Shifts', href: '/hr-management/attendance', icon: Clock3 },
          { name: 'Meetings', href: '/hr-management/meetings', icon: CalendarDays },
        ],
      },
      {
        name: 'Policy Management',
        href: '/policy-management',
        icon: ShieldCheck,
        implemented: true,
        description: 'Create and edit policies for the Users frontend site and every staff role.',
        capabilities: [
          'Users (Frontend) policies appear on the customer website',
          'Create policies per staff role (vendor, delivery, farmer…)',
          'Edit or delete existing policies anytime',
          'Publish so the matching role panel / site shows them instantly',
          'Keep drafts hidden until ready',
        ],
      },
    ],
  },
  {
    id: 'government',
    label: 'Government',
    items: [
      {
        name: 'All Govt Schemes',
        href: '/government/schemes',
        icon: Landmark,
        end: true,
        implemented: true,
        description: 'Browse and manage all government agricultural schemes.',
      },
      {
        name: 'Create Govt Schemes',
        href: '/government/schemes/create',
        icon: PlusCircle,
        implemented: true,
        description: 'Add a new government scheme for farmers.',
      },
      {
        name: 'All Applications',
        href: '/government/applications',
        icon: ClipboardList,
        implemented: true,
        description: 'Every farmer and the government schemes they applied for.',
      },
    ],
  },
  {
    id: 'finance',
    label: 'Finance',
    items: [
      {
        name: 'Finance Management',
        href: '/finance',
        icon: Landmark,
        description: 'Payouts, settlements, GST, and store-wise financial overview.',
        capabilities: [
          'View store and vendor settlements',
          'Track payouts, invoices, and GST summaries',
          'Reconcile collections vs orders',
          'Export finance reports for accounting',
        ],
      },
      {
        name: 'Reports',
        href: '/reports',
        icon: BarChart3,
        description: 'Sales, inventory, delivery, and vendor reports with date filters.',
        capabilities: [
          'Sales and revenue reports by store',
          'Inventory movement and stock-out reports',
          'Delivery performance and SLA reports',
          'Vendor and promotion performance reports',
        ],
      },
    ],
  },
];
