/// Serviceable cities & areas (Blinkit-style quick-commerce markets).
abstract final class ServiceLocations {
  static const cities = <ServiceCity>[
    ServiceCity(
      id: 'mumbai',
      name: 'Mumbai',
      state: 'Maharashtra',
      areas: [
        'Andheri East',
        'Andheri West',
        'Bandra',
        'Powai',
        'Worli',
        'Lower Parel',
        'Dadar',
        'Thane West',
        'Navi Mumbai',
        'Malad',
        'Goregaon',
        'Borivali',
        'Chembur',
        'Ghatkopar',
        'Colaba',
      ],
    ),
    ServiceCity(
      id: 'delhi',
      name: 'Delhi NCR',
      state: 'Delhi',
      areas: [
        'Connaught Place',
        'Saket',
        'Dwarka',
        'Rohini',
        'Laxmi Nagar',
        'South Extension',
        'Karol Bagh',
        'Mayur Vihar',
        'Vasant Kunj',
        'Pitampura',
        'Noida Sector 18',
        'Noida Sector 62',
        'Gurugram Cyber City',
        'Gurugram Sector 29',
        'Ghaziabad Indirapuram',
      ],
    ),
    ServiceCity(
      id: 'bengaluru',
      name: 'Bengaluru',
      state: 'Karnataka',
      areas: [
        'Koramangala',
        'Indiranagar',
        'Whitefield',
        'HSR Layout',
        'Jayanagar',
        'BTM Layout',
        'Electronic City',
        'Marathahalli',
        'Yelahanka',
        'Malleshwaram',
        'Rajajinagar',
        'Hebbal',
        'Banashankari',
        'Sarjapur Road',
        'MG Road',
      ],
    ),
    ServiceCity(
      id: 'hyderabad',
      name: 'Hyderabad',
      state: 'Telangana',
      areas: [
        'Hitech City',
        'Gachibowli',
        'Madhapur',
        'Banjara Hills',
        'Jubilee Hills',
        'Kukatpally',
        'Secunderabad',
        'Ameerpet',
        'Kondapur',
        'Miyapur',
        'LB Nagar',
        'Dilsukhnagar',
        'Manikonda',
        'Begumpet',
        'Uppal',
      ],
    ),
    ServiceCity(
      id: 'chennai',
      name: 'Chennai',
      state: 'Tamil Nadu',
      areas: [
        'T Nagar',
        'Anna Nagar',
        'Adyar',
        'Velachery',
        'OMR',
        'Porur',
        'Tambaram',
        'Nungambakkam',
        'Mylapore',
        'Kodambakkam',
        'Chromepet',
        'Sholinganallur',
        'Guindy',
        'Perungudi',
        'Ambattur',
      ],
    ),
    ServiceCity(
      id: 'pune',
      name: 'Pune',
      state: 'Maharashtra',
      areas: [
        'Hinjewadi',
        'Baner',
        'Aundh',
        'Kothrud',
        'Viman Nagar',
        'Kharadi',
        'Hadapsar',
        'Wakad',
        'Pimple Saudagar',
        'FC Road',
        'Koregaon Park',
        'Magarpatta',
        'Bavdhan',
        'Warje',
        'Camp',
      ],
    ),
    ServiceCity(
      id: 'kolkata',
      name: 'Kolkata',
      state: 'West Bengal',
      areas: [
        'Salt Lake',
        'Park Street',
        'New Town',
        'Ballygunge',
        'Howrah',
        'Behala',
        'Dum Dum',
        'Garia',
        'Rajarhat',
        'Tollygunge',
        'Esplanade',
        'Lake Town',
        'Jadavpur',
        'Kasba',
        'Alipore',
      ],
    ),
    ServiceCity(
      id: 'ahmedabad',
      name: 'Ahmedabad',
      state: 'Gujarat',
      areas: [
        'Navrangpura',
        'Satellite',
        'Bopal',
        'SG Highway',
        'Maninagar',
        'Prahlad Nagar',
        'Vastrapur',
        'CG Road',
        'Chandkheda',
        'Gota',
        'Thaltej',
        'Paldi',
        'Iscon',
        'Science City',
        'Bodakdev',
      ],
    ),
    ServiceCity(
      id: 'jaipur',
      name: 'Jaipur',
      state: 'Rajasthan',
      areas: [
        'Malviya Nagar',
        'Vaishali Nagar',
        'C Scheme',
        'Raja Park',
        'Mansarovar',
        'Jagatpura',
        'Tonk Road',
        'Bani Park',
        'Ajmer Road',
        'Sitapura',
        'Vidhyadhar Nagar',
        'Pink City',
        'Civil Lines',
        'Sanganer',
        'Jhotwara',
      ],
    ),
    ServiceCity(
      id: 'lucknow',
      name: 'Lucknow',
      state: 'Uttar Pradesh',
      areas: [
        'Gomti Nagar',
        'Hazratganj',
        'Aliganj',
        'Indira Nagar',
        'Aminabad',
        'Alambagh',
        'Chowk',
        'Mahanagar',
        'Rajajipuram',
        'Ashiyana',
        'Jankipuram',
        'Vikas Nagar',
        'Nishatganj',
        'LDA Colony',
        'Sushant Golf City',
      ],
    ),
    ServiceCity(
      id: 'chandigarh',
      name: 'Chandigarh',
      state: 'Chandigarh',
      areas: [
        'Sector 17',
        'Sector 22',
        'Sector 35',
        'Sector 43',
        'Industrial Area',
        'Manimajra',
        'Panchkula',
        'Mohali Phase 3B2',
        'Mohali Sector 70',
        'Zirakpur',
        'Sector 8',
        'Sector 9',
        'Sector 26',
        'Sector 34',
        'IT Park',
      ],
    ),
    ServiceCity(
      id: 'indore',
      name: 'Indore',
      state: 'Madhya Pradesh',
      areas: [
        'Vijay Nagar',
        'AB Road',
        'Palasia',
        'Rajendra Nagar',
        'Bhawarkua',
        'Sapna Sangeeta',
        'Old Palasia',
        'New Palasia',
        'Scheme 78',
        'Scheme 54',
        'Sudama Nagar',
        'Rau',
        'MR 10',
        'Bengali Square',
        'Geeta Bhawan',
      ],
    ),
    ServiceCity(
      id: 'noida',
      name: 'Noida',
      state: 'Uttar Pradesh',
      areas: [
        'Sector 18',
        'Sector 62',
        'Sector 50',
        'Sector 137',
        'Sector 76',
        'Sector 63',
        'Sector 16',
        'Sector 27',
        'Sector 44',
        'Sector 93',
        'Greater Noida West',
        'Knowledge Park',
        'Alpha 1',
        'Alpha 2',
        'Pari Chowk',
      ],
    ),
    ServiceCity(
      id: 'gurugram',
      name: 'Gurugram',
      state: 'Haryana',
      areas: [
        'Cyber City',
        'Sector 29',
        'Sector 54',
        'Golf Course Road',
        'Sohna Road',
        'MG Road',
        'DLF Phase 1',
        'DLF Phase 2',
        'DLF Phase 3',
        'Sector 14',
        'Sector 15',
        'Sector 56',
        'Udyog Vihar',
        'Palam Vihar',
        'New Gurgaon',
      ],
    ),
  ];

  static ServiceCity? byId(String id) {
    for (final city in cities) {
      if (city.id == id) return city;
    }
    return null;
  }

  static List<ServiceCity> search(String query) {
    final q = query.trim().toLowerCase();
    if (q.isEmpty) return cities;
    return cities
        .where(
          (c) =>
              c.name.toLowerCase().contains(q) ||
              c.state.toLowerCase().contains(q) ||
              c.id.contains(q),
        )
        .toList();
  }
}

class ServiceCity {
  const ServiceCity({
    required this.id,
    required this.name,
    required this.state,
    required this.areas,
  });

  final String id;
  final String name;
  final String state;
  final List<String> areas;
}
